- name: Ensure prom dependencies are installed.
  package:
    name:
      - python3-pip
      - virtualenv
      - lsb-release
      - python3-setuptools
      - mysql-client
    state: present
    update_cache: yes

- name: Ensure group nogroup exists for prom docker
  ansible.builtin.group:
    name: nogroup
    state: present

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    mode: '0750'
    owner: "root"
    group: "nogroup"
  loop:
    - '/usr/local/bin/prometheus-docker'
    - '/usr/local/bin/prometheus-docker/prometheus'
    - '/usr/local/bin/prometheus-docker/prometheus/config'
    - '/usr/local/bin/prometheus-docker/prometheus/data'
    - '/usr/local/bin/prometheus-docker/snmp-exporter'

- name: copy needed prom files
  copy:
    src: "{{ item.src_file }}"
    dest: "{{ item.dest_file }}"
    mode: "750"
    owner: "root"
    group: "nogroup"
  loop:
    - { src_file: 'docker-compose.yml', dest_file: '/usr/local/bin/prometheus-docker/docker-compose.yml' }
    - { src_file: 'prometheus.yml', dest_file: '/usr/local/bin/prometheus-docker/prometheus/config/prometheus.yml' }
    - { src_file: 'prom.json', dest_file: '/usr/local/bin/prometheus-docker/prometheus/config/prom.json' }
    - { src_file: 'snmp.yml', dest_file: '/usr/local/bin/prometheus-docker/snmp-exporter/snmp.yml' }

- name: enable and start docker
  ansible.builtin.service:
    name: docker
    enabled: yes
    state: started

- name: restart prometheus docker containers
  shell: |
    docker compose down
    docker compose build
    docker compose up -d    
  args:
    chdir: /usr/local/bin/prometheus-docker
